version: '3.8'
services:
  order-management:
    build: .
    container_name: order-management
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_CONNECTION_LIMIT: 10
      USER_MANAGEMENT_URL: 'http://localhost:3000'
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: order-management-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5